server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    metadata-map:
      prometheus.scrape: "true"

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: proveedor-service
          uri: lb://proveedor-service
          predicates:
            - Path=/proveedor/**
        - id: grasa-service
          uri: lb://grasa-service
          predicates:
            - Path=/grasa/**
        - id: leche-service
          uri: lb://leche-service
          predicates:
            - Path=/leche/**
        - id: pago-service
          uri: lb://pago-service
          predicates:
            - Path=/pago/**
management:
  endpoints:
    web:
      exposure:
        include: "*"
