server:
  port: ${PORT:${SERVER_PORT:0}}

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    metadataMap:
      prometheus.scrape: true

spring:
  cors:
    allowed-origins: "http://localhost:8080"
    allowed-methods: "*"
    allowed-headers: "*"
    allow-credentials: true

